project:
  type: book
  output-dir: docs


book:
  title: "ECS200 - Research Methods in Ecology"
  subtitle: "School of Environmental and Conservation Sciences, Murdoch University"
  author: "Nicholas Wu"
  date: today
  date-format: Do MMM YYYY
  favicon: images/MU_CREST_Red.png
  chapters:
    - index.qmd
    - week1_getting_started.qmd
    - week2_tidy_data.qmd
    - week3_diversity_index.qmd
    - week4_descriptive_stats.qmd
    - references.qmd
    - the_islands.qmd
  navbar:
    search: true
    logo: images/MU_CREST_Red.png

bibliography: ./bib/references.bib
csl: ./bib/the-journal-of-experimental-biology.csl
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

#fontsize: 95%;

#linkcolor: "#e12744" 



name: Deploy Quarto Book to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
